---

- stream:
    name: openstack
    module: rallyci.streams.gerrit
    ssh:
      username: CHANGEME
      hostname: review.openstack.org
    vote: false
    silent: true
    fake-stream: tests/test-stream.yaml
    comment-header: |
      Build {succeeded} by RallyCI. Use "my-ci recheck" to recheck
    comment-job-template: "- {name} http://example.com/{log_path}/ : {success} in {time}"
    recheck-regexp: ^my-ci recheck$
    env:
      GERRIT_PROJECT: change.project
      GERRIT_REF: patchSet.ref

- provider:
    name: my_virsh
    module: rallyci.providers.virsh
    hosts:
      - hostname: 10.1.1.1
        port: 16622
    max_vms: 4
    storage:
      backend: btrfs
      path: /ci/rally
    metadata_server:
      listen_addr: 127.0.0.1
      listen_port: 8081
      authorized_keys: /etc/rally-ci/authorized_keys
      user_data: |
        #!/bin/sh
        cat /home/ubuntu/.ssh/authorized_keys > /root/.ssh/authorized_keys
    images:
      bare_u1404:
        url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
      dev:
        parent: bare_u1404
        build-scripts: ["init_ubuntu_dev", "clone_projects"]
    vms:
      dev:
        image: dev
        memory: 512
        net: ["virbr0", "tmpbr% 02:01:01:01:01:01"]

- service:
    name: status
    module: rallyci.services.status
    listen: ["localhost", "8080"]

- script:
    name: init_ubuntu_dev
    interpreter: /bin/bash -xe -s
    data: |
      apt-get -y update && apt-get -y upgrade && apt-get -y install git
      apt-get -y remove cloud-init
      mkdir /etc/skel/.ssh
      cp /root/.ssh/authorized_keys /etc/skel/.ssh/
      useradd -m rally
      echo 'rally ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/rally-42

- script:
    name: clone_projects
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      mkdir openstack-dev
      cd openstack-dev
      git clone git://git.openstack.org/openstack-dev/ci-sandbox.git

- script:
    name: git_checkout
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd $GERRIT_PROJECT && git checkout master && git pull
      git fetch https://review.openstack.org/$GERRIT_PROJECT $GERRIT_REF
      git checkout FETCH_HEAD && git rebase master || true
      git clean -fxd -e .tox -e *.egg-info
      git diff --name-only master

- script:
    name: run_tests
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      env && ls && echo "Hello world"
      cd $GERRIT_PROJECT
      git status

- job:
    name: test
    env:
      RCI_TOX_ENV: py27 # TODO
    runner:
      module: rallyci.runners.ssh
      provider: my_virsh
      vms:
        - name: dev
          scripts: ["git_checkout", "run_tests"]
          scp: ["/var/log/", "varlog"]
        - name: dev
          scripts: ["git_checkout", "run_tests"]

- project:
    name: openstack-dev/ci-sandbox
    jobs:
      - test
