---

- stream:
    name: openstack
    module: rallyci.streams.gerrit
    ssh:
      username: redixin
      hostname: review.openstack.org
    vote: false
    silent: true
    fake-stream: tests/test-stream.yaml
    comment-header: |
      Build {succeeded} by RallyCI. Use "my-ci recheck" to recheck
    comment-job-template: "- {name} http://example.com/{log_path}/ : {success} in {time}"
    recheck-regexp: ^my-ci recheck$

- env: # TODO: move it to stream
    name: event
    module: rallyci.environments.event
    export-event:
      GERRIT_PROJECT: change.project
      GERRIT_REF: patchSet.ref

- env: # TODO: embed this
    name: dummy
    module: rallyci.environments.dummy

- script:
    name: git_checkout
    interpreter: /bin/bash -xe -s
    data: |
      env
      cd $GERRIT_PROJECT && git checkout master && git pull
      git fetch https://review.openstack.org/$GERRIT_PROJECT $GERRIT_REF
      git checkout FETCH_HEAD && git rebase master || true
      git clean -fxd -e .tox -e *.egg-info
      git diff --name-only master

- script:
    name: init_ubuntu_dev
    interpreter: /bin/bash -xe -s
    data: |
      apt-get -y update && apt-get -y upgrade
      apt-get -y install git python-setuptools python-pip
      apt-get -y remove cloud-init
      mkdir /etc/skel/.ssh
      cp /root/.ssh/authorized_keys /etc/skel/.ssh/
      useradd -m rally
      echo 'rally ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/rally-42

- script:
    name: install_rally
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      git clone git://git.openstack.org/openstack/rally.git

- script:
    name: rally_unit
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd rally
      python -m unittest discover tests/unit

- provider:
    name: my_virsh
    module: rallyci.providers.virsh
    hosts:
      - hostname: localhost
    max_vms: 4
    storage:
      backend: btrfs
      path: /ci/rally
    metadata_server:
      listen_addr: 127.0.0.1 # 169.254.169.254
      listen_port: 8081 # 80
      authorized_keys: /etc/rally-ci/authorized_keys
      user_data: |
        #!/bin/sh
        cat /home/ubuntu/.ssh/authorized_keys > /root/.ssh/authorized_keys
    images:
      bare_u1404:
        url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
      dev:
        parent: bare_u1404
        build-scripts: ["init_ubuntu_dev", "install_rally"]
    vms:
      dev:
        image: dev
        memory: 1024
        net: ["virbr0"]

- job:
    name: unit
    envs:
      - name: event
      - name: dummy
        export:
          RCI_TOX_ENV: py27
    runner:
      module: rallyci.runners.ssh
      provider: my_virsh
      vms:
        - name: dev
          scripts: ["git_checkout", "rally_unit"]

- project:
    name: openstack-dev/ci-sandbox
    jobs:
      - unit
