---

- stream:
    name: openstack
    module: rallyci.streams.gerrit
    ssh:
      username: redixin
      hostname: review.openstack.org
    vote: false
    silent: true
    fake-stream: tests/test-stream.yaml
    comment-header: |
      Build {succeeded} by RallyCI. Use "my-ci recheck" to recheck
    comment-job-template: "- {name} http://example.com/{log_path}/ : {success} in {time}"
    recheck-regexp: ^my-ci recheck$

- env: # TODO: move it to stream
    name: event
    module: rallyci.environments.event
    export-event:
      GERRIT_PROJECT: change.project
      GERRIT_REF: patchSet.ref

- env: # embed this
    name: dummy
    module: rallyci.environments.dummy

- script:
    name: git_checkout
    interpreter: /bin/bash -xe -s
    data: |
      cd $GERRIT_PROJECT && git checkout master && git pull
      git fetch https://review.openstack.org/$GERRIT_PROJECT $GERRIT_REF
      git checkout FETCH_HEAD && git rebase master || true
      git clean -fxd -e .tox -e *.egg-info
      git diff --name-only master

- script:
    name: init_ubuntu_dev
    interpreter: /bin/bash -xe -s
    data: |
      apt-get -y update && apt-get -y upgrade
      apt-get -y install git

- script:
    name: install_rally
    interpreter: /bin/bash -xe -s
    data: |
      cd rally
      python setup.py build
      python setup.py install

- script:
    name: rally_unit
    interpreter: /bin/bash -xe -s
    user: rally
    data: |
      cd rally
      python -m unittest discover tests/unit

- provider:
    name: my_virsh
    module: rallyci.providers.virsh
    nodes:
      - hostname: localhost
    max_vms: 4
    storage:
      backend: zfs
      dataset: all/ci
    metadata_server:
      listen_addr: 127.0.0.1 # 169.254.169.254
      listen_port: 8081 # 80
      authorized_keys: /etc/rally-ci/authorized_keys
      user_data: |
        #!/bin/sh
        cat /home/ubuntu/.ssh/authorized_keys > /root/.ssh/authorized_keys
    images:
      u1404:
        url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
      u1404_dsvm:
        parent: u1404
        build-scripts: ["init_dsvm"]
      u1404_rally:
        parent: u1404
        build-scripts: ["install_rally"]
      mos-1:
        source: mos1@1
      mos-2:
        source: mos2@1
      mos-3:
        source: mos3@1

    vms:
      dsvm:
        image: dsvm
        memory: 3000
        net: ["virbr0"]
      mos-1:
        image: mos-1
        memory: 4096
        net: ["mos%"]
      mos-2:
        image: mos-2
        memory: 4096
        net: ["mos%"]
      rally-mos:
        memory: 3000
        image: u1404_rally
        net: ["virbr0", "mos%"]

- job:
    name: py27
    envs:
      - name: event
      - name: dummy
        export:
          RCI_TOXENV: py27
    runner:
      module: rallyci.runners.ssh
      provider: my_virsh
      vms:
        - name: rally-mos
          scripts: ["rally_unit"]
        - name: rally-mos
          scripts: ["rally_unit"]

- project:
    name: openstack-dev/ci-sandbox
    jobs:
      - py27
