---
- stream:
    name: test
    module: rallyci.streams.fake
    path: resources/gerrit-sample-stream.json

- status:
    name: main
    module: rallyci.status.http
    listen: [0.0.0.0, 8080]

- logger:
    name: file
    module: rallyci.loggers.logfile
    path: /home/rally/simulation-logs/

- env:
    name: event
    module: rallyci.environments.event
    export-event:
      GERRIT_PROJECT: change.project
      GERRIT_REF: patchSet.ref

- env:
    name: dummy
    module: rallyci.environments.dummy

- nodepool:
    name: test
    module: rallyci.nodepools.fair
    tasks_per_node: 8
    nodes:
      - hostname: host1
        username: user1
      - hostname: host2
        username: user2

- runner:
    name: fake
    nodepool: test
    module: rallyci.runners.fake
    sleep-build: [2, 4]
    sleep-run: [4, 8]

- script:
    name: script1
    interpreter: /bin/bash -xe -s
    data: |
      echo "script 1"

- script:
    name: script2
    interpreter: /bin/bash -xe -s
    data:
      echo "script 2"

- job:
    name: job1
    envs:
      - name: event
      - name: dummy
        export:
          RCI_TOXENV: py27
    runner:
      name: fake
      scripts:
        - script1
        - script2

- job:
    name: job2
    envs:
      - name: event
      - name: dummy
        export:
          RCI_TOXENV: py34
    runner:
      name: fake
      scripts:
        - script1

- project:
    name: openstack/rally
    jobs: ["job1", "job2"]

- project:
    name: openstack/neutron
    jobs: ["job1"]
